### ISSUE TITLE
Amplitude Certificate Error

### ISSUE THREAD

**Issue by benspring** [geoffdutton/amplitude#14]
https://status.amplitude.com/

There has been a certificate chain problem on the amplitude API, they have a new API (api2.amplitude.com), can you update your library to use this for the time being?

**Comment by Strafer14** [comment]
I have opened a pr that fixes it, hopefully the repository owner(@geoffdutton) approves soon.

**Comment by jeetkr** [comment]
yes, AMPLITUDE_TOKEN_ENDPOINT needs to be updated to api2.amplitude.com in amplitude.js

**Comment by geoffdutton** [comment]
v5.1.1 published to address this: https://www.npmjs.com/package/amplitude
