### ISSUE TITLE
Support for Amplitude HTTP API v2

### ISSUE THREAD

**Issue by geoffdutton** [geoffdutton/amplitude#4]
This is from the previous [maintainer's issue](https://github.com/crookedneighbor/amplitude/issues/79) from @harytkon:

> Amplitude deprecates HTTP API v1.
> https://help.amplitude.com/hc/en-us/articles/360032842391-HTTP-API-V2
> 
> Any plans to provide support for HTTP API v2?

**Comment by StErMi** [comment]
Do you have an eta for it?

**Comment by geoffdutton** [comment]
I don't have an ETA for it. It looks like a very well documented API, which is good.

@StErMi Do you think it makes sense to do like, `const Amplitude = require('amplitude/v2')`, and leave the current one as is?

I think I'd also like to incorporate typescript per #7 as part of this.

**Comment by StErMi** [comment]
Hi @geoffdutton, to be honest, I don't think you should support it. Maybe make a tag (release) for the v1 e one for the v2 but the v1 is already deprecated and does not support many of the new features of the v2 so people (without any changes) should be able to update the newest.

**Comment by geoffdutton** [comment]
@StErMi  Here is the start of typescript(#7)/v2: https://www.npmjs.com/package/amplitude/v/5.0.1-next.4

It's still a work in progress, but let me know what you think. Thanks!

**Comment by geoffdutton** [comment]
Hello all. V2 is implemented on next:

```npm install amplitude@next```

I'm slowly trying it out in production, let me know if you see any issues.
