### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by StErMi** [geoffdutton/amplitude#7]
Will you add support to Typescript? I would really love to have it!

**Comment by geoffdutton** [comment]
I just started working on this today, I'd love to be able to support it. I don't have a ton of experience, so I'm definitely open to any suggestions, but I hope to having a branch up this week for feedback.

**Comment by geoffdutton** [comment]
Here's what I've got so far: https://github.com/geoffdutton/amplitude/tree/add-typescript

Do you have any experience with Typescript? Would welcome any feedback.

**Comment by StErMi** [comment]
Hi @geoffdutton I can share the snippet of the basic library I've made to handle the v2 API with typescript if you want

**Comment by geoffdutton** [comment]
Yeah that'd be great.

**Comment by geoffdutton** [comment]
Hello all. V2 with Typescript is implemented on next:

```npm install amplitude@next```

I'm slowly trying it out in production, let me know if you see any issues.

**Comment by geoffdutton** [comment]
@StErMi [v5.0.2](https://www.npmjs.com/package/amplitude/v/5.0.2) has officially been released! Let me know if you see any issues.
